# Generated by Django 5.1.3 on 2024-11-13 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jobpost_date_jobpost_description_jobpost_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='tilte',
            new_name='title',
        ),
    ]
